#!/bin/bash

echo -e "\033[1;34m <..Installing pingmaster..>  \033[0m"

# Setup storage for Termux
termux-setup-storage

# Install necessary packages
pkg install -y wget python
pip install tqdm ping3

# Copy the main script to the appropriate location
cp pingmaster.py $PREFIX/bin/pingmaster

# Give execute permissions to the script
chmod +x $PREFIX/bin/pingmaster

echo -e "\033[1;32mScript executed successfully \033[0m"
echo -e "\033[1;33mType 'pingmaster' to run \033[0m"
